name: Publish on GitHub, CurseForge & Modrinth    
 
on: [ workflow_dispatch ]           

env:                                              
  MINECRAFT_VERSION: 1.21                        
  JAVA_VERSION: 21      
  VERSION: 1.5.0.1+1.21  
  RELEASE_NAME: v1.5.0.1+1.21
  MODRINTH_TOKEN: ${{ secrets.RINTHMOD }}
      
permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
          
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3                                   
        with:
          modrinth-id: JOJwCjjz                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md                                      

          loaders: fabric, quilt
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
          dependencies: |
              fish-lib(embedded)
              fstats-api(embedded)
         # dependencies: |
        #      
